# Generated by Django 2.1.1 on 2018-10-13 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('settled_at', models.DateField()),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WGBalance.AccountingPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=60)),
                ('comment', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WGBalance.Bill')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_creator', to='WGBalance.Person')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_creditor', to='WGBalance.Person')),
                ('debitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_debitor', to='WGBalance.Person')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_creditor', to='WGBalance.Person'),
        ),
        migrations.AddField(
            model_name='bill',
            name='debitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_debitor', to='WGBalance.Person'),
        ),
    ]
